# np.sort

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 5, 76, 11, 10, 87, 94, 51, 97, 59, 41, 28, 46, 29, 36, 74])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[83, 90, 74, 49],
       [81, 89, 64, 29],
       [55, 96, 40, 51],
       [14, 37, 10, 22],
       [94, 88, 29, 99],
       [ 8, 61, 10, 89]])

In [3]:
np.sort(a)[::-1]

array([97, 94, 87, 76, 74, 59, 51, 46, 41, 36, 29, 28, 11, 10,  5])

In [4]:
np.sort(b,axis=0)

array([[ 8, 37, 10, 22],
       [14, 61, 10, 29],
       [55, 88, 29, 49],
       [81, 89, 40, 51],
       [83, 90, 64, 89],
       [94, 96, 74, 99]])

# np.append

In [5]:
# code
np.append(a,200)

array([  5,  76,  11,  10,  87,  94,  51,  97,  59,  41,  28,  46,  29,
        36,  74, 200])

In [6]:
b

array([[83, 90, 74, 49],
       [81, 89, 64, 29],
       [55, 96, 40, 51],
       [14, 37, 10, 22],
       [94, 88, 29, 99],
       [ 8, 61, 10, 89]])

In [7]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[83.        , 90.        , 74.        , 49.        ,  0.73859612],
       [81.        , 89.        , 64.        , 29.        ,  0.81701723],
       [55.        , 96.        , 40.        , 51.        ,  0.16608918],
       [14.        , 37.        , 10.        , 22.        ,  0.39821352],
       [94.        , 88.        , 29.        , 99.        ,  0.71959973],
       [ 8.        , 61.        , 10.        , 89.        ,  0.63184891]])

# np.concatenate

In [8]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique

In [11]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims

In [13]:
# code
a.shape

(15,)

In [14]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [15]:
np.expand_dims(a,axis=1)

array([[ 5],
       [76],
       [11],
       [10],
       [87],
       [94],
       [51],
       [97],
       [59],
       [41],
       [28],
       [46],
       [29],
       [36],
       [74]])

# np.where

In [16]:
a

array([ 5, 76, 11, 10, 87, 94, 51, 97, 59, 41, 28, 46, 29, 36, 74])

In [17]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  4,  5,  6,  7,  8, 14], dtype=int64),)

In [18]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 5,  0, 11, 10,  0,  0,  0,  0,  0, 41, 28, 46, 29, 36,  0])

In [19]:
np.where(a%2 == 0,0,a)

array([ 5,  0, 11,  0, 87,  0, 51, 97, 59, 41,  0,  0, 29,  0,  0])

# np.argmax

In [20]:
a

array([ 5, 76, 11, 10, 87, 94, 51, 97, 59, 41, 28, 46, 29, 36, 74])

In [21]:
b

array([[83, 90, 74, 49],
       [81, 89, 64, 29],
       [55, 96, 40, 51],
       [14, 37, 10, 22],
       [94, 88, 29, 99],
       [ 8, 61, 10, 89]])

In [22]:
np.argmax(a)

7

In [23]:
np.argmax(b,axis=0)

array([4, 2, 0, 4], dtype=int64)

In [24]:
np.argmax(b,axis=1)

array([1, 1, 1, 1, 3, 3], dtype=int64)

In [25]:
# np.argmin
np.argmin(a)


0

# np.cumsum

In [27]:
a


array([ 5, 76, 11, 10, 87, 94, 51, 97, 59, 41, 28, 46, 29, 36, 74])

In [28]:
b

array([[83, 90, 74, 49],
       [81, 89, 64, 29],
       [55, 96, 40, 51],
       [14, 37, 10, 22],
       [94, 88, 29, 99],
       [ 8, 61, 10, 89]])

In [29]:
np.cumsum(a)

array([  5,  81,  92, 102, 189, 283, 334, 431, 490, 531, 559, 605, 634,
       670, 744])

In [30]:
b

array([[83, 90, 74, 49],
       [81, 89, 64, 29],
       [55, 96, 40, 51],
       [14, 37, 10, 22],
       [94, 88, 29, 99],
       [ 8, 61, 10, 89]])

In [31]:
np.cumsum(b,axis=1)

array([[ 83, 173, 247, 296],
       [ 81, 170, 234, 263],
       [ 55, 151, 191, 242],
       [ 14,  51,  61,  83],
       [ 94, 182, 211, 310],
       [  8,  69,  79, 168]])

In [32]:
np.cumsum(b,axis=0)

array([[ 83,  90,  74,  49],
       [164, 179, 138,  78],
       [219, 275, 178, 129],
       [233, 312, 188, 151],
       [327, 400, 217, 250],
       [335, 461, 227, 339]])

In [33]:
# np.cumprod
np.cumprod(a)

array([          5,         380,        4180,       41800,     3636600,
         341840400,   253991216, -1132655824,  1892783120,   294696592,
        -338430016,  1612088448,  -494075264,  -606840320, -1956510720])

In [34]:
a

array([ 5, 76, 11, 10, 87, 94, 51, 97, 59, 41, 28, 46, 29, 36, 74])

# np.percentile

In [35]:
a

array([ 5, 76, 11, 10, 87, 94, 51, 97, 59, 41, 28, 46, 29, 36, 74])

In [36]:
np.percentile(a,50)

46.0

In [37]:
np.median(a)

46.0

# np.histogram 

In [39]:
a

array([ 5, 76, 11, 10, 87, 94, 51, 97, 59, 41, 28, 46, 29, 36, 74])

In [40]:
np.histogram(a,bins=[0,50,100])

(array([8, 7], dtype=int64), array([  0,  50, 100]))

# np.corrcoef

In [42]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin

In [43]:
a

array([ 5, 76, 11, 10, 87, 94, 51, 97, 59, 41, 28, 46, 29, 36, 74])

In [44]:
b

array([[83, 90, 74, 49],
       [81, 89, 64, 29],
       [55, 96, 40, 51],
       [14, 37, 10, 22],
       [94, 88, 29, 99],
       [ 8, 61, 10, 89]])

In [45]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([10])

# np.flip

In [46]:
a

array([ 5, 76, 11, 10, 87, 94, 51, 97, 59, 41, 28, 46, 29, 36, 74])

In [47]:
np.flip(a)

array([74, 36, 29, 46, 28, 41, 59, 97, 51, 94, 87, 10, 11, 76,  5])

In [48]:
b

array([[83, 90, 74, 49],
       [81, 89, 64, 29],
       [55, 96, 40, 51],
       [14, 37, 10, 22],
       [94, 88, 29, 99],
       [ 8, 61, 10, 89]])

In [49]:
np.flip(b,axis=1)

array([[49, 74, 90, 83],
       [29, 64, 89, 81],
       [51, 40, 96, 55],
       [22, 10, 37, 14],
       [99, 29, 88, 94],
       [89, 10, 61,  8]])

In [50]:
np.flip(b,axis=0)

array([[ 8, 61, 10, 89],
       [94, 88, 29, 99],
       [14, 37, 10, 22],
       [55, 96, 40, 51],
       [81, 89, 64, 29],
       [83, 90, 74, 49]])

# np.put

In [51]:
a

array([ 5, 76, 11, 10, 87, 94, 51, 97, 59, 41, 28, 46, 29, 36, 74])

In [52]:
np.put(a,[0,1],[110,530])

In [53]:
a

array([110, 530,  11,  10,  87,  94,  51,  97,  59,  41,  28,  46,  29,
        36,  74])

# np.delete

In [54]:
a

array([110, 530,  11,  10,  87,  94,  51,  97,  59,  41,  28,  46,  29,
        36,  74])

In [55]:
np.delete(a,[0,2,4])

array([530,  10,  94,  51,  97,  59,  41,  28,  46,  29,  36,  74])

# Set functions

In [56]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
np.intersect1d(m,n)

array([3, 4, 5])

In [58]:
np.setdiff1d(n,m)

array([6, 7])

In [59]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [60]:
m[np.in1d(m,1)]

array([1])

# np.clip

In [61]:
a

array([110, 530,  11,  10,  87,  94,  51,  97,  59,  41,  28,  46,  29,
        36,  74])

In [62]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 25, 75, 75, 51, 75, 59, 41, 28, 46, 29, 36, 74])